/** Utilitários Tailwind compartilhados pelo workspace interno. */
export const adminUi = {
  contents: 'contents',
  root: 'min-h-screen bg-brand-background text-brand-text',
  page: 'min-h-screen bg-brand-background',
  topbar: 'flex flex-wrap items-center justify-between gap-3 border-b border-[#eee] bg-white px-6 py-4',
  topbarLeft: 'flex items-center gap-5',
  status: 'mr-3 text-[13px] text-brand-muted',
  chipSuccess:
    'mr-3 inline-flex items-center rounded-full bg-success/10 px-2.5 py-0.5 text-[12px] font-semibold text-success',
  button: 'cursor-pointer rounded-md border border-[#ddd] bg-white px-3 py-2 text-[13px] font-semibold text-brand-text transition-[background,color,border-color,transform] hover:border-brand-primary hover:text-brand-primary active:scale-95 disabled:cursor-not-allowed disabled:opacity-60',
  primaryButton: 'cursor-pointer rounded-md border-0 bg-brand-primary px-3 py-2 text-[13px] font-semibold text-white transition-[background,transform] hover:bg-brand-primary-dark active:scale-95 disabled:cursor-not-allowed disabled:opacity-60',
  dangerButton: 'cursor-pointer rounded-md border border-[#dba0a0] bg-white px-3 py-2 text-[13px] font-semibold text-[#b00020] transition-[background,transform] hover:bg-[#fff1f1] active:scale-95',
  iconButton: 'flex size-8 cursor-pointer items-center justify-center rounded-md border border-transparent bg-transparent p-0 text-brand-muted transition-[background,color,border-color,transform] hover:border-brand-primary/20 hover:bg-brand-primary/8 hover:text-brand-primary active:scale-95 disabled:cursor-not-allowed disabled:opacity-50',
  field: 'flex flex-col gap-1 [&>label]:text-xs [&>label]:text-brand-muted [&>input]:rounded-lg [&>input]:border [&>input]:border-[#ddd] [&>input]:bg-white [&>input]:px-3 [&>input]:py-2.5 [&>input]:text-sm [&>select]:rounded-lg [&>select]:border [&>select]:border-[#ddd] [&>select]:bg-white [&>select]:px-3 [&>select]:py-2.5 [&>select]:text-sm',
  fieldRow: 'flex gap-3 max-sm:flex-col [&>.field]:min-w-0 [&>.field]:flex-1',
  hint: 'text-[13px] text-brand-muted',
  builderLayout: 'hidden min-h-[calc(100dvh-5.75rem)] lg:flex',
  builderAiPanel: 'border-b border-border bg-surface px-4 py-4 sm:px-6',
  builderAiForm: 'mx-auto flex max-w-6xl flex-col gap-3 lg:flex-row lg:items-end',
  builderHistory: 'mx-auto mt-3 max-w-6xl rounded-control border border-border bg-brand-background/50 p-3',
  canvasWrap: 'min-w-0 flex-1 overflow-auto px-4 pt-5 pb-8 sm:px-6',
  canvas: 'relative min-h-[680px] min-w-[1200px] rounded-brand border border-border bg-[#f4f4f5] p-5 shadow-card [background-image:linear-gradient(to_right,rgba(24,24,27,.07)_1px,transparent_1px),linear-gradient(to_bottom,rgba(24,24,27,.07)_1px,transparent_1px)] [background-size:20px_20px]',
  toolbox: 'w-[300px] shrink-0 overflow-y-auto border-l border-border bg-surface p-5',
  toolboxList: 'flex flex-col gap-2.5',
  toolItem: 'flex cursor-grab items-center gap-3 rounded-control border border-border bg-surface p-3 text-left text-sm font-semibold shadow-card transition-[border-color,box-shadow,transform] hover:border-brand-primary/30 hover:shadow-md active:cursor-grabbing active:scale-[.98]',
  emptyCanvas: 'flex min-h-[300px] flex-col items-center justify-center rounded-brand border-2 border-dashed border-[#d4d4d8] p-6 text-center text-brand-muted',
  blockCard: 'absolute flex min-h-[120px] flex-col overflow-hidden rounded-brand border border-border bg-surface shadow-card transition-[border-color,box-shadow,opacity]',
  blockHeader: 'flex min-h-10 items-center gap-2 border-b border-border bg-surface px-2 py-1.5',
  blockHandle: 'flex size-7 cursor-grab items-center justify-center rounded-control text-brand-muted transition-colors hover:bg-brand-background hover:text-brand-primary active:cursor-grabbing',
  blockLabel: 'flex-1 overflow-hidden text-[11px] font-semibold text-ellipsis whitespace-nowrap text-brand-muted',
  blockPreview: 'min-h-0 flex-1 overflow-hidden pointer-events-none',
  resizeH: 'absolute right-0 bottom-0 left-0 flex h-3 cursor-ns-resize items-center justify-center after:h-0.5 after:w-8 after:rounded-full after:bg-brand-primary/30',
  resizeW: 'absolute top-0 right-0 bottom-0 flex w-3 cursor-ew-resize items-center justify-center after:h-8 after:w-0.5 after:rounded-full after:bg-brand-primary/30',
  resizeCorner: 'absolute right-0 bottom-0 size-4 cursor-nwse-resize bg-brand-primary/20',
  panelHeader: 'mb-4 flex items-center justify-between border-b border-[#eee] pb-3',
  positionFields: 'mb-4 rounded-lg bg-brand-background p-3',
  itemCard: 'flex flex-col gap-3 rounded-control border border-border bg-surface p-3',
  previewEmpty: 'text-[13px] text-brand-muted',
  previewBlock: 'flex size-full min-h-[120px] items-center justify-center bg-brand-background p-4 text-center text-[13px] text-brand-muted',
  catalogPage: 'min-h-screen bg-brand-background',
  catalogGrid: 'grid grid-cols-[repeat(auto-fill,minmax(180px,1fr))] gap-3',
  productCard: 'overflow-hidden rounded-brand bg-white shadow-[0_1px_4px_rgba(0,0,0,.08)]',
  collectionsPage: 'min-h-screen bg-brand-background',
  collectionsSidebar: 'w-full border-b border-[#eee] bg-white p-4 md:w-[280px] md:shrink-0 md:border-r md:border-b-0',
  collectionsList: 'flex flex-col gap-1',
  collectionItem: 'flex items-center rounded-lg border border-transparent',
  collectionItemButton: 'flex flex-1 cursor-pointer items-center justify-between bg-transparent px-3 py-2 text-left text-sm hover:text-brand-primary',
  collectionCount: 'text-xs text-brand-muted',
  collectionsNew: 'mt-4 border-t border-[#eee] pt-4',
  collectionsEditor: 'min-w-0 flex-1 p-6',
  subheading: 'mt-6 mb-2 text-base font-bold',
  productList: 'flex flex-col gap-2',
  productRow: 'flex items-center gap-3 rounded-lg border border-[#eee] bg-white p-3',
  productInfo: 'min-w-0 flex-1',
  productName: 'block overflow-hidden text-sm font-semibold text-ellipsis whitespace-nowrap',
  productPrice: 'text-[13px] text-brand-muted',
  productPicker: 'rounded-lg border border-[#eee] bg-white p-3',
  productPickerResults: 'mt-2 flex max-h-[260px] flex-col gap-1 overflow-y-auto',
  productPickerResult: 'flex cursor-pointer items-center gap-2 rounded-md px-2 py-2 text-left hover:bg-brand-background',
  sharePanel: 'mt-6 rounded-brand border border-[#eee] bg-white p-4',
  shareLinkRow: 'flex gap-2 [&>input]:min-w-0 [&>input]:flex-1 [&>input]:rounded-lg [&>input]:border [&>input]:border-[#ddd] [&>input]:px-3 [&>input]:py-2',
  shareActions: 'mt-3 flex flex-wrap gap-2',
  toolsList: 'grid grid-cols-[repeat(auto-fill,minmax(220px,1fr))] gap-4 p-6',
  toolRow: 'rounded-brand bg-white p-4 shadow-[0_1px_4px_rgba(0,0,0,.08)]',
  productsEditor: 'p-6',
  defaultMarkup: 'mb-5 rounded-brand border border-[#eee] bg-white p-4',
  overridesList: 'flex flex-col gap-3',
  overrideCard: 'rounded-brand border border-[#eee] bg-white p-4',
  overrideRow: 'flex flex-wrap items-end gap-3',
  overrideActions: 'flex items-center gap-2',
  similarField: 'rounded-lg border border-[#eee] bg-white',
  similarToggle: 'flex w-full cursor-pointer items-center justify-between border-0 bg-transparent p-3 text-left text-sm font-semibold',
  similarBody: 'border-t border-[#eee] p-3',
  toggle: 'relative h-6 w-10 cursor-pointer rounded-full border-0 bg-[#ccc] transition-colors',
  toggleKnob: 'absolute top-0.5 left-0.5 size-5 rounded-full bg-white shadow transition-transform',
  tiers: 'flex flex-col gap-2',
  tierRow: 'flex flex-wrap items-end gap-2 rounded-lg border border-[#eee] p-3',
  modalOverlay: 'fixed inset-0 z-[80] flex items-center justify-center bg-black/45 p-5',
  modalPanel: 'w-full max-w-[640px] rounded-brand bg-white shadow-[0_12px_40px_rgba(0,0,0,.25)]',
  modalHeader: 'flex items-center justify-between border-b border-[#eee] p-4',
  modalBody: 'max-h-[70vh] overflow-y-auto p-4',
  modalFooter: 'flex justify-end gap-2 border-t border-[#eee] p-4',
  table: 'w-full border-collapse text-left text-sm [&_th]:border-b [&_th]:border-[#eee] [&_th]:p-3 [&_th]:text-brand-muted [&_td]:border-b [&_td]:border-[#f0f0f0] [&_td]:p-3',
} as const;
