/**
 * Tokens de apresentação reutilizáveis. Cada valor contém somente utilitários
 * Tailwind; não há acoplamento com folhas de estilo globais.
 */
export const publicUi = {
  contents: 'contents',
  container: 'mx-auto max-w-[1200px] px-4 sm:px-5',
  primaryButton: 'cursor-pointer rounded-md border-0 bg-brand-primary px-4 py-2.5 text-sm font-semibold text-white transition-[background,color,opacity,transform] hover:bg-brand-primary-dark active:scale-95 disabled:cursor-not-allowed disabled:bg-[#ccc]',
  subtleButton: 'cursor-pointer rounded-lg border border-[#ccc] bg-transparent px-3.5 py-2.5 text-sm text-brand-muted transition-[border-color,color,transform] hover:border-brand-primary hover:text-brand-primary active:scale-95',
  field: 'flex flex-col gap-1',
  fieldRow: 'flex gap-3 max-sm:flex-col',
  input: 'rounded-lg border border-[#ddd] bg-white px-3 py-2.5 text-sm text-brand-text outline-none focus:border-brand-primary',
  muted: 'text-[13px] text-brand-muted',
  error: 'm-0 text-[13px] text-[#c0392b]',
  card: 'flex flex-col overflow-hidden rounded-brand bg-brand-card shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
  overlay: 'fixed inset-0 z-[60] bg-black/40',
  drawerRight: 'fixed inset-y-0 right-0 z-[61] flex w-[min(380px,100%)] translate-x-full flex-col bg-white transition-transform duration-[250ms]',
  drawerLeft: 'fixed inset-y-0 left-0 z-[61] w-[min(300px,85vw)] -translate-x-full overflow-hidden bg-white transition-transform duration-[250ms]',
  drawerHeader: 'flex items-center justify-between border-b border-[#eee] p-4',
  drawerBody: 'flex flex-1 flex-col gap-2 overflow-y-auto p-4',
  empty: 'p-5 text-center text-[13px] text-brand-muted',
  topnav: 'sticky top-0 z-15 grid min-h-16 grid-cols-[44px_1fr_auto] items-center border-b border-border bg-surface/95 px-3 backdrop-blur sm:px-5',
  topnavBrand: 'min-w-0 justify-self-center overflow-hidden text-ellipsis whitespace-nowrap text-center text-base font-extrabold tracking-[-0.02em] text-brand-primary',
  topnavLinks: 'flex items-center gap-1 text-sm md:gap-4 md:[&>a]:block max-md:[&>a]:hidden',
  topnavCart: 'flex min-h-11 min-w-11 cursor-pointer items-center justify-center gap-1.5 rounded-control border-0 bg-transparent text-base hover:bg-brand-background',
  topnavLogin: 'cursor-pointer border-0 bg-transparent text-[13px] text-brand-muted hover:text-brand-primary',
  count: 'rounded-full bg-brand-primary px-1.5 py-px text-xs text-white',
  menuTrigger: 'flex size-8 cursor-pointer flex-col justify-center gap-1 border-0 bg-transparent p-1.5 [&>span]:block [&>span]:h-0.5 [&>span]:w-full [&>span]:rounded [&>span]:bg-brand-text',
  sidePanel: 'absolute inset-0 flex flex-col overflow-y-auto bg-white transition-transform duration-[250ms]',
  sideHeader: 'flex items-center justify-end px-5 pt-4 pb-1 [&>button]:cursor-pointer [&>button]:border-0 [&>button]:bg-transparent [&>button]:text-xl',
  sideSection: 'flex flex-col border-t border-[#f0f0f0] px-5 py-2.5 first:border-t-0',
  sideLink: 'py-2 text-sm text-brand-text hover:text-brand-primary',
  sideSearch: 'px-5 pt-2 pb-4',
  sideSearchToggle: 'flex cursor-pointer border-0 bg-transparent py-1.5 text-brand-text',
  sideSearchBox: 'mt-2.5 [&>input]:w-full [&>input]:border-0 [&>input]:border-b [&>input]:border-[#ddd] [&>input]:bg-transparent [&>input]:py-2 [&>input]:text-sm [&>input]:outline-none [&>input]:focus:border-brand-text',
  sideSearchResult: 'flex items-center gap-2.5 border-t border-[#f5f5f5] py-2.5 [&>img]:h-[45px] [&>img]:w-9 [&>img]:shrink-0 [&>img]:rounded-sm [&>img]:bg-[#f2f2f2] [&>img]:object-cover',
  controls: 'sticky top-0 z-5 my-5 flex flex-wrap items-center gap-2.5 bg-brand-background py-3',
  search: 'min-w-[200px] flex-[2] rounded-lg border border-[#ddd] bg-white px-3 py-2.5 text-sm',
  select: 'min-w-[140px] flex-1 rounded-lg border border-[#ddd] bg-white px-3 py-2.5 text-sm',
  resultCount: '-mt-2 mb-3 text-[13px] text-brand-muted',
  grid: 'grid grid-cols-2 gap-3 pb-12 sm:gap-4 md:grid-cols-3 lg:grid-cols-4',
  cartItem: 'flex gap-2.5 border-b border-[#f0f0f0] py-2.5 [&>img]:aspect-[9/16] [&>img]:w-14 [&>img]:rounded-md [&>img]:bg-[#eee] [&>img]:object-cover',
  cartItemInfo: 'flex-1 [&>.name]:text-[13px] [&>.name]:font-semibold [&>.variant]:text-xs [&>.variant]:text-brand-muted',
  qtyRow: 'mt-1 flex items-center gap-1.5 [&>button]:size-[22px] [&>button]:cursor-pointer [&>button]:rounded-[4px] [&>button]:border [&>button]:border-[#ddd] [&>button]:bg-white',
  cartFooter: 'border-t border-[#eee] p-4',
  cartTotal: 'flex justify-between py-1 text-sm font-bold [&.subtotal]:font-normal [&.discount]:text-[#2e8b57]',
  whatsapp: 'mt-2 w-full cursor-pointer rounded-md border-0 bg-[#25d366] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#1da851]',
  checkoutButton: 'mt-2 w-full cursor-pointer rounded-md border-0 bg-brand-primary px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-primary-dark',
  hint: 'mt-2 text-[11px] leading-[1.4] text-brand-muted',
  checkoutSteps: 'my-5 flex flex-wrap gap-2 text-[13px] text-brand-muted',
  checkoutStep: 'text-brand-muted',
  checkoutSeparator: 'ml-2 text-[#ccc]',
  checkoutItems: 'mb-4 flex flex-col gap-1 rounded-brand bg-brand-card px-4 py-2 shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
  checkoutSummary: 'mb-4 flex flex-col gap-1.5 rounded-brand bg-brand-card px-4 py-3.5 shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
  summaryLine: 'flex justify-between text-sm text-brand-muted',
  checkoutActions: 'mb-4 flex max-w-[360px] flex-col gap-2.5',
  loginPage: 'flex min-h-screen items-center justify-center bg-brand-background p-5',
  loginForm: 'flex w-full max-w-[340px] flex-col gap-3.5 rounded-brand bg-brand-card p-7 shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
  authSwitch: 'm-0 text-center text-[13px] text-brand-muted [&>a]:font-semibold [&>a]:text-brand-primary',
  productDetail: 'grid grid-cols-2 gap-8 py-6 max-md:grid-cols-1',
  gallery: 'min-w-0',
  detailImage: 'aspect-[9/16] w-full rounded-brand bg-[#eee] object-cover',
  detailInfo: 'flex flex-col gap-3',
  sectionTitle: 'mb-2 text-lg font-bold',
  modal: 'fixed inset-0 z-80 flex items-center justify-center bg-black/45 p-5',
  modalPanel: 'w-full max-w-[420px] rounded-brand bg-white p-[22px] shadow-[0_12px_40px_rgba(0,0,0,0.25)]',
  talaoCard: 'relative flex cursor-pointer items-center gap-3 rounded-brand border border-[#eee] bg-white p-3 text-left transition-[border-color,transform] hover:border-brand-primary active:scale-[.98]',
  talaoActive: 'animate-[talao-active-swap_.45s_ease] border-brand-primary bg-brand-primary text-white',
  talaoLabel: 'mt-2.5 text-[11px] tracking-[.04em] text-brand-muted uppercase first:mt-0',
  talaoInfo: 'flex min-w-0 flex-1 flex-col',
  talaoName: 'overflow-hidden text-sm font-semibold text-ellipsis whitespace-nowrap',
  talaoChannel: 'text-[11px] opacity-75',
  talaoMeta: 'flex shrink-0 flex-col items-end text-xs',
  talaoStatus: 'rounded-full bg-[#ffe6a8] px-2 py-0.5 text-[10px] font-bold tracking-[.02em] text-[#8a5a00] uppercase',
  presence: 'fixed bottom-4 left-4 z-[55] flex items-end gap-2.5 animate-[presence-in_.4s_ease-out]',
  presenceAvatar: 'flex size-11 cursor-pointer items-center justify-center rounded-full border-0 bg-brand-primary text-[17px] font-bold text-white shadow-[0_2px_10px_rgba(0,0,0,.22)] hover:bg-brand-primary-dark',
  presenceMessage: 'flex max-w-[min(280px,60vw)] items-center gap-2 rounded-full bg-brand-card py-2.5 pr-2 pl-4 text-[13px] leading-[1.3] shadow-[0_2px_10px_rgba(0,0,0,.16)]',
  pdfPage: 'mx-auto max-w-[1000px] px-4 py-6',
  pdfToolbar: 'mb-5 flex items-center gap-4 border-b border-[#eee] pb-4 print:hidden',
  pdfGrid: 'grid grid-cols-[repeat(auto-fill,minmax(160px,1fr))] gap-4',
  pdfItem: 'break-inside-avoid [&>img]:block [&>img]:aspect-[9/16] [&>img]:w-full [&>img]:rounded-md [&>img]:bg-[#eee] [&>img]:object-cover',
  backLink: 'my-4 inline-block text-sm font-semibold text-brand-primary hover:underline',
  priceLocked: 'my-1 block text-[13px] font-semibold text-brand-primary',
  originalPrice: 'relative text-sm text-brand-muted after:absolute after:inset-x-0 after:top-1/2 after:h-px after:bg-current',
  discountedPrice: 'text-xl font-bold text-brand-primary',
  discountRow: 'my-0.5 flex flex-wrap items-center gap-2',
  discountBadge: 'rounded-full bg-brand-primary px-1.5 py-0.5 text-[11px] font-bold text-white',
  cartHeader: 'flex items-center justify-between border-b border-[#eee] p-4 [&>button]:cursor-pointer [&>button]:border-0 [&>button]:bg-transparent [&>button]:text-xl',
  cartItems: 'flex-1 overflow-y-auto px-4 py-2',
  remove: 'ml-2.5 cursor-pointer border-0 bg-transparent text-xs text-[#b00020] hover:underline',
  cartGroup: 'border-b border-[#f0f0f0] py-3',
  cartGroupSummary: 'flex items-center gap-2.5',
  cartGroupInfo: 'flex-1 [&>.name]:text-[13px] [&>.name]:font-semibold [&>.variant]:text-xs [&>.variant]:text-brand-muted',
  cartGroupToggle: 'cursor-pointer border-0 bg-transparent p-1 text-brand-primary hover:underline',
  cartGroupItems: 'mt-2.5 flex flex-col gap-2.5',
  cartGroupEdit: 'mt-2 cursor-pointer self-start border-0 bg-transparent p-0 text-xs font-semibold text-brand-primary hover:underline disabled:opacity-40',
  cartLine: 'flex flex-wrap items-center gap-3.5 gap-y-2.5 [&>img]:aspect-[9/16] [&>img]:w-10 [&>img]:shrink-0 [&>img]:rounded-[5px] [&>img]:bg-[#eee] [&>img]:object-cover',
  cartLineField: 'flex shrink-0 flex-col gap-1 [&>label]:text-[10px] [&>label]:tracking-[.03em] [&>label]:text-brand-muted [&>label]:uppercase [&>select]:min-w-28 [&>select]:rounded-md [&>select]:border [&>select]:border-[#ddd] [&>select]:bg-white [&>select]:px-2 [&>select]:py-1.5 [&>select]:text-xs',
  cartLineGrid: 'flex flex-1 flex-wrap items-center gap-3',
  cartLineCell: 'flex min-w-[30px] flex-col items-center gap-1 text-[11px] text-brand-muted [&>.size]:font-semibold [&>.size]:text-brand-text',
  cartLinePrice: 'shrink-0 text-right text-xs whitespace-nowrap text-brand-muted',
  cartLineAction: 'shrink-0 cursor-pointer border-0 bg-transparent p-0 text-[11px] text-brand-primary hover:underline disabled:cursor-default disabled:opacity-40',
  cartLineTrash: 'shrink-0 cursor-pointer border-0 bg-transparent p-1 text-[15px] leading-none text-brand-muted hover:text-[#b00020]',
  cartProduct: 'border-b border-[#f0f0f0] py-3.5 last:border-b-0',
  cartProductHeader: 'mb-2.5 flex items-baseline gap-2 [&>.name]:text-[13px] [&>.name]:font-semibold',
  cartProductLines: 'flex flex-col gap-2.5',
  cartAddColor: 'mt-2.5 cursor-pointer rounded-full border border-dashed border-[#ccc] bg-transparent px-3.5 py-1.5 text-xs text-brand-muted hover:border-brand-primary hover:text-brand-primary',
  colorSelect: 'relative',
  colorSelectTrigger: 'flex min-w-28 cursor-pointer items-center gap-1.5 rounded-md border border-[#ddd] bg-white px-2 py-1.5 text-xs text-brand-text hover:border-brand-primary disabled:cursor-default disabled:opacity-50',
  colorSelectList: 'absolute top-[calc(100%+4px)] left-0 z-5 m-0 flex max-h-[220px] min-w-40 list-none flex-col overflow-y-auto rounded-lg border border-[#ddd] bg-white p-1 shadow-[0_4px_16px_rgba(0,0,0,0.12)]',
  colorSelectOption: 'flex w-full cursor-pointer items-center gap-2 rounded-md border-0 bg-transparent px-2 py-1.5 text-left text-xs text-brand-text hover:bg-[#f5f5f5]',
  swatch: 'inline-block size-3 shrink-0 rounded-full border border-black/15',
  homeFallback: 'static h-auto overflow-hidden bg-linear-to-br from-brand-primary to-brand-primary-dark px-4 py-9 text-center text-white [&>div]:static [&>div]:flex [&>div]:flex-col [&>div]:items-center [&>div]:justify-center [&>div>h1]:mb-1.5 [&>div>h1]:text-[clamp(22px,4vw,36px)]',
  homeSections: 'relative mx-auto h-[var(--canvas-height,auto)] max-w-[1200px] max-sm:flex max-sm:h-auto max-sm:flex-col max-sm:gap-4 max-sm:px-4',
  homeSectionItem: 'absolute left-[var(--x,0px)] top-[var(--y,0px)] h-[var(--h,auto)] w-[var(--w,100%)] overflow-hidden max-sm:static max-sm:h-auto max-sm:w-full max-sm:overflow-visible',
  catalogFooter: 'mt-10 border-t border-border bg-surface text-foreground',
  catalogFooterGrid: 'grid gap-8 py-10 sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1.2fr] lg:gap-12 lg:py-12',
  catalogFooterBrand: 'max-w-sm [&>h2]:mt-1 [&>h2]:text-xl [&>h2]:font-extrabold [&>h2]:tracking-[-0.03em] [&>h2]:text-brand-primary [&>p:last-child]:mt-3 [&>p:last-child]:text-sm [&>p:last-child]:leading-6 [&>p:last-child]:text-muted-foreground',
  catalogFooterEyebrow: 'text-xs font-bold tracking-[0.12em] text-muted-foreground uppercase',
  catalogFooterSection: 'flex flex-col items-start gap-1 [&>h2]:mb-2 [&>h2]:text-sm [&>h2]:font-bold [&>a]:flex [&>a]:min-h-11 [&>a]:items-center [&>a]:gap-2 [&>a]:text-sm [&>a]:text-muted-foreground [&>a]:transition-colors [&>a:hover]:text-brand-primary [&>p]:flex [&>p]:min-h-7 [&>p]:items-center [&>p]:gap-2 [&>p]:text-sm [&>p]:leading-5 [&>p]:text-muted-foreground',
  catalogFooterHours: '!mt-1 !text-xs !leading-5',
  catalogFooterBottom: 'flex flex-col gap-3 border-t border-border py-5 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between [&>nav]:flex [&>nav]:gap-4 [&>nav>a]:underline-offset-4 [&>nav>a:hover]:text-brand-primary [&>nav>a:hover]:underline',
  quickviewHeader: 'flex items-center justify-between border-b border-[#eee] p-4',
  quickviewBody: 'flex-1 overflow-y-auto p-4',
  miniCart: 'flex cursor-pointer items-center gap-2 border-0 bg-transparent p-0 text-[13px] font-semibold whitespace-nowrap text-brand-text',
  presenceMinimize: 'flex size-[22px] cursor-pointer items-center justify-center rounded-full border-0 bg-transparent text-base text-brand-muted hover:bg-brand-background hover:text-brand-text',
  ordersPage: 'pb-[60px]',
  ordersList: 'flex flex-col gap-3',
  orderCard: 'rounded-brand bg-brand-card p-4 shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
  orderCardHeader: 'mb-2 flex flex-wrap items-center justify-between gap-2',
  orderItems: 'flex flex-col gap-2.5',
  orderItem: 'flex gap-2.5 [&>img]:aspect-[9/16] [&>img]:w-14 [&>img]:rounded-md [&>img]:bg-[#eee] [&>img]:object-cover',
  paymentOptions: 'mb-5 flex max-w-[360px] flex-col gap-2.5',
  paymentOption: 'flex cursor-pointer items-center gap-2.5 rounded-brand border-2 border-transparent bg-brand-card px-4 py-3.5 text-sm font-semibold shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
} as const;
