/**
 * Tokens de apresentação reutilizáveis. Cada valor contém somente utilitários
 * Tailwind; não há acoplamento com folhas de estilo globais.
 */
export const publicUi = {
  contents: 'contents',
  container: 'mx-auto max-w-[1200px] px-4 sm:px-5',
  catalogMain: 'relative pb-14 sm:pb-16',
  primaryButton: 'cursor-pointer rounded-md border-0 bg-brand-primary px-4 py-2.5 text-sm font-semibold text-white transition-[background,color,opacity,transform] hover:bg-brand-primary-dark active:scale-95 disabled:cursor-not-allowed disabled:bg-[#ccc]',
  subtleButton: 'cursor-pointer rounded-lg border border-[#ccc] bg-transparent px-3.5 py-2.5 text-sm text-brand-muted transition-[border-color,color,transform] hover:border-brand-primary hover:text-brand-primary active:scale-95',
  field: 'flex flex-col gap-1 [&>label]:text-sm [&>label]:font-medium [&>label]:text-brand-text [&>input]:w-full [&>input]:rounded-md [&>input]:border [&>input]:border-neutral-300 [&>input]:bg-white [&>input]:px-3 [&>input]:py-2.5 [&>input]:text-sm [&>input]:text-brand-text [&>input]:outline-none [&>input]:placeholder:text-neutral-400 [&>input]:focus:border-brand-primary [&>input]:focus:ring-2 [&>input]:focus:ring-brand-primary/15',
  fieldRow: 'flex gap-3 max-sm:flex-col',
  input: 'rounded-lg border border-[#ddd] bg-white px-3 py-2.5 text-sm text-brand-text outline-none focus:border-brand-primary',
  muted: 'text-[13px] text-brand-muted',
  error: 'm-0 text-[13px] text-[#c0392b]',
  card: 'flex flex-col overflow-hidden rounded-brand bg-brand-card shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
  overlay: 'fixed inset-0 z-[60] bg-black/40',
  drawerRight: 'fixed inset-y-0 right-0 z-[61] flex w-[min(380px,100%)] flex-col bg-white transition-transform duration-[250ms]',
  drawerLeft: 'fixed inset-y-0 left-0 z-[61] w-[min(300px,85vw)] -translate-x-full overflow-hidden bg-white transition-transform duration-[250ms]',
  drawerHeader: 'flex items-center justify-between border-b border-[#eee] p-4',
  drawerIconButton: 'flex size-9 cursor-pointer items-center justify-center rounded-control border-0 bg-transparent text-brand-muted transition-[background,color,transform] hover:bg-brand-primary/8 hover:text-brand-primary active:scale-95',
  drawerBody: 'flex flex-1 flex-col gap-2.5 overflow-y-auto p-4',
  empty: 'p-5 text-center text-[13px] text-brand-muted',
  topnav: 'sticky top-0 z-15 grid min-h-16 grid-cols-[44px_1fr_auto] items-center border-b border-border bg-surface/95 px-3 backdrop-blur sm:px-5',
  topnavBrand: 'min-w-0 justify-self-center overflow-hidden text-ellipsis whitespace-nowrap text-center text-base font-extrabold tracking-[-0.02em] text-brand-primary',
  topnavLinks: 'flex items-center gap-1 text-sm md:gap-4 md:[&>a]:block max-md:[&>a]:hidden',
  topnavCart: 'flex min-h-11 min-w-11 cursor-pointer items-center justify-center gap-1.5 rounded-control border-0 bg-transparent text-base hover:bg-brand-background',
  topnavLogin: 'cursor-pointer border-0 bg-transparent text-[13px] text-brand-muted hover:text-brand-primary max-md:!flex max-md:min-h-11 max-md:items-center max-md:justify-center max-md:rounded-control max-md:px-2.5 max-md:hover:bg-brand-background',
  topnavProfile: 'flex min-w-0 items-center gap-2 rounded-control px-1 py-1 text-left',
  topnavProfileInfo: 'hidden min-w-0 text-right sm:block',
  topnavProfileName: 'm-0 max-w-32 overflow-hidden text-ellipsis whitespace-nowrap text-xs font-semibold text-brand-text',
  topnavProfileRole: 'm-0 text-[11px] text-brand-muted',
  topnavAvatar: 'flex size-9 shrink-0 items-center justify-center overflow-hidden rounded-full bg-brand-primary text-xs font-bold text-white',
  count: 'rounded-full bg-brand-primary px-1.5 py-px text-xs text-white',
  menuTrigger: 'flex size-8 cursor-pointer flex-col justify-center gap-1 border-0 bg-transparent p-1.5 [&>span]:block [&>span]:h-0.5 [&>span]:w-full [&>span]:rounded [&>span]:bg-brand-text',
  sidePanel: 'absolute inset-0 flex flex-col overflow-y-auto bg-white transition-transform duration-[250ms]',
  sideHeader: 'flex items-center justify-end px-5 pt-4 pb-1 [&>button]:cursor-pointer [&>button]:border-0 [&>button]:bg-transparent [&>button]:text-xl',
  sideSection: 'flex flex-col border-t border-[#f0f0f0] px-5 py-2.5 first:border-t-0',
  sideLink: 'py-2 text-sm text-brand-text hover:text-brand-primary',
  sideSearch: 'px-5 pt-2 pb-4',
  sideSearchToggle: 'flex cursor-pointer border-0 bg-transparent py-1.5 text-brand-text',
  sideSearchBox: 'mt-2.5 [&>input]:w-full [&>input]:border-0 [&>input]:border-b [&>input]:border-[#ddd] [&>input]:bg-transparent [&>input]:py-2 [&>input]:text-sm [&>input]:outline-none [&>input]:focus:border-brand-text',
  sideSearchResult: 'flex items-center gap-2.5 border-t border-[#f5f5f5] py-2.5 [&>img]:h-[45px] [&>img]:w-9 [&>img]:shrink-0 [&>img]:rounded-sm [&>img]:bg-[#f2f2f2] [&>img]:object-cover',
  controls: 'sticky top-0 z-5 my-5 flex flex-wrap items-center gap-2.5 bg-brand-background py-3',
  search: 'min-w-[200px] flex-[2] rounded-lg border border-[#ddd] bg-white px-3 py-2.5 text-sm',
  select: 'min-w-[140px] flex-1 rounded-lg border border-[#ddd] bg-white px-3 py-2.5 text-sm',
  resultCount: '-mt-2 mb-3 text-[13px] text-brand-muted',
  grid: 'grid grid-cols-2 gap-3 pb-12 sm:gap-4 md:grid-cols-3 lg:grid-cols-4',
  catalogToolbar: 'sticky top-0 z-10 -mx-4 mb-5 border-b border-border bg-surface-muted/90 px-4 py-3 backdrop-blur-xl md:static md:mx-0 md:mb-0 md:border-0 md:bg-transparent md:px-0 md:py-0',
  catalogLayout: 'md:grid md:grid-cols-[220px_1fr] md:items-start md:gap-8 lg:grid-cols-[248px_1fr] lg:gap-10',
  catalogSidebar: 'md:sticky md:top-20',
  catalogSidebarTitle: 'mb-3 text-sm font-bold tracking-[.02em] text-brand-text uppercase',
  catalogFilterGroup: 'flex flex-col gap-3',
  catalogContent: 'min-w-0',
  catalogResults: 'mb-4 flex items-center justify-between gap-3 text-[13px] text-brand-muted',
  catalogGrid: 'grid grid-cols-2 gap-3 pb-12 sm:gap-4 md:grid-cols-3 lg:grid-cols-4',
  catalogTabs: 'sticky top-16 z-10 -mx-4 mb-6 flex items-end gap-5 overflow-x-auto border-b border-border bg-surface-muted/90 px-4 pt-3 backdrop-blur-xl [scrollbar-width:none] sm:-mx-5 sm:px-5 md:mx-0 md:px-2 [&::-webkit-scrollbar]:hidden',
  catalogTab: 'relative shrink-0 cursor-pointer border-0 bg-transparent px-0 pb-3.5 text-sm font-semibold whitespace-nowrap text-brand-muted transition-colors hover:text-brand-text',
  catalogTabActive: 'text-brand-primary',
  catalogTabUnderline: 'pointer-events-none absolute bottom-[-1px] left-0 h-0.5 bg-brand-primary transition-[transform,width] duration-300 ease-out',
  catalogSection: 'scroll-mt-32 pt-1 mb-9',
  catalogSectionTitle: 'mb-3.5 text-lg font-bold text-brand-text',
  catalogCard: 'group flex min-w-0 flex-col overflow-hidden rounded-brand border border-border/60 bg-brand-card shadow-[0_1px_3px_rgba(44,28,36,.06)] transition-[border-color,box-shadow,transform] duration-300 ease-out hover:-translate-y-1 hover:border-brand-primary/25 hover:shadow-[0_16px_34px_rgba(44,28,36,.12)]',
  catalogCardMedia: 'relative aspect-[9/16] overflow-hidden bg-brand-background',
  catalogCardContent: 'flex flex-1 flex-col gap-2 p-3.5 sm:p-4',
  carouselControl: 'inline-flex size-9 cursor-pointer items-center justify-center rounded-full border border-white/20 bg-black/35 text-white shadow-sm backdrop-blur-sm transition-[background,transform,border-color] duration-200 hover:scale-105 hover:border-white/35 hover:bg-black/55 active:scale-95 disabled:cursor-not-allowed disabled:opacity-40',
  cartItem: 'flex gap-2.5 border-b border-[#f0f0f0] py-2.5',
  cartItemImage: 'h-[72px] w-14 shrink-0 rounded-md bg-[#eee]',
  cartItemInfo: 'flex-1 [&>.name]:text-[13px] [&>.name]:font-semibold [&>.variant]:text-xs [&>.variant]:text-brand-muted',
  qtyRow: 'mt-1 flex items-center gap-1.5 [&>button]:size-[22px] [&>button]:cursor-pointer [&>button]:rounded-[4px] [&>button]:border [&>button]:border-[#ddd] [&>button]:bg-white',
  cartFooter: 'border-t border-[#eee] p-4',
  cartTotal: 'flex justify-between py-1 text-sm font-bold [&.subtotal]:font-normal [&.discount]:text-[#2e8b57]',
  whatsapp: 'mt-2 w-full cursor-pointer rounded-md border-0 bg-[#25d366] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#1da851]',
  checkoutButton: 'mt-2 w-full cursor-pointer rounded-md border-0 bg-brand-primary px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-primary-dark',
  hint: 'mt-2 text-[11px] leading-[1.4] text-brand-muted',
  checkoutSteps: 'my-5 flex flex-wrap gap-2 text-[13px] text-brand-muted',
  checkoutStep: 'text-brand-muted',
  checkoutSeparator: 'ml-2 text-[#ccc]',
  checkoutItems: 'mb-4 flex flex-col gap-1 rounded-brand bg-brand-card px-4 py-2 shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
  checkoutSummary: 'mb-4 flex flex-col gap-1.5 rounded-brand bg-brand-card px-4 py-3.5 shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
  summaryLine: 'flex justify-between text-sm text-brand-muted',
  checkoutActions: 'mb-4 flex max-w-[360px] flex-col gap-2.5',
  loginPage: 'min-h-svh bg-brand-background px-4 py-8 sm:px-6 sm:py-12 lg:py-24',
  loginForm: 'mx-auto flex w-full max-w-[450px] flex-col gap-4 rounded-brand bg-brand-card p-6 shadow-[0_1px_4px_rgba(0,0,0,0.08)] lg:border lg:border-solid lg:border-neutral-300 lg:p-8',
  authSwitch: 'm-0 text-center text-[13px] text-brand-muted [&>a]:font-semibold [&>a]:text-brand-primary',
  productDetail: 'grid grid-cols-2 gap-8 py-6 max-md:grid-cols-1',
  gallery: 'flex min-w-0 gap-2',
  galleryThumbRail: 'flex shrink-0 flex-col gap-2 overflow-y-auto',
  galleryThumb: 'aspect-[4/5] w-11 shrink-0 cursor-pointer rounded-md ring-1 ring-[#eee] transition-[box-shadow] hover:ring-brand-primary sm:w-14',
  galleryMainWrap: 'relative min-w-0 flex-1',
  galleryNavButton: 'absolute top-1/2 z-10 flex size-7 -translate-y-1/2 cursor-pointer items-center justify-center rounded-full border-0 bg-white/90 text-foreground shadow-[0_1px_4px_rgba(0,0,0,0.2)] hover:bg-white',
  galleryNavButtonPrev: 'left-1.5',
  galleryNavButtonNext: 'right-1.5',
  detailImage: 'aspect-[9/16] w-full rounded-brand bg-[#eee] object-cover',
  detailInfo: 'flex flex-col gap-3',
  sectionTitle: 'mb-2 text-lg font-bold',
  modal: 'fixed inset-0 z-80 flex items-center justify-center bg-black/45 p-5',
  modalPanel: 'w-full max-w-[420px] rounded-brand bg-white p-[22px] shadow-[0_12px_40px_rgba(0,0,0,0.25)]',
  talaoCard: 'group relative flex w-full cursor-pointer items-center gap-3 rounded-brand border border-[#eee] bg-white p-3 text-left shadow-[0_1px_2px_rgba(0,0,0,0.03)] transition-[border-color,box-shadow,transform] hover:border-brand-primary hover:shadow-[0_4px_16px_rgba(0,0,0,0.08)] active:scale-[.98]',
  talaoCardClosed: 'opacity-70',
  talaoActive: 'group relative flex w-full cursor-pointer items-center gap-3 rounded-brand border text-left transition-[border-color,box-shadow,transform] active:scale-[.98] animate-[talao-active-swap_.45s_ease] border-brand-primary bg-brand-primary p-4 text-white shadow-[0_8px_24px_rgba(24,24,27,0.22)] hover:shadow-[0_10px_28px_rgba(24,24,27,0.28)]',
  talaoLabel: 'mt-2.5 text-[11px] tracking-[.04em] text-brand-muted uppercase first:mt-0',
  talaoInfo: 'flex min-w-0 flex-1 flex-col',
  talaoName: 'overflow-hidden text-sm font-semibold text-ellipsis whitespace-nowrap',
  talaoChannel: 'text-[11px] opacity-75',
  talaoMeta: 'flex shrink-0 flex-col items-end text-xs text-brand-muted [&>*:last-child]:font-semibold [&>*:last-child]:text-brand-text',
  talaoMetaActive: 'flex shrink-0 flex-col items-end text-xs opacity-90 [&>*:last-child]:text-sm [&>*:last-child]:font-bold [&>*:last-child]:opacity-100',
  talaoArrowButton: 'flex size-8 shrink-0 items-center justify-center rounded-full bg-white/15 text-white transition-colors group-hover:bg-white/25',
  talaoStatus: 'rounded-full bg-[#ffe6a8] px-2 py-0.5 text-[10px] font-bold tracking-[.02em] text-[#8a5a00] uppercase',
  talaoAddRow: 'flex items-center gap-2',
  talaoSearchWrap: 'relative flex-1',
  talaoSearchIcon: 'pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-brand-muted',
  talaoSearchInput: 'w-full rounded-full border border-[#ddd] bg-white py-2.5 pr-3 pl-9 text-sm text-brand-text outline-none focus:border-brand-primary',
  talaoAddButton: 'flex shrink-0 cursor-pointer items-center gap-1.5 rounded-full border-0 bg-brand-primary px-4 py-2.5 text-sm font-semibold whitespace-nowrap text-white transition-[background,transform] hover:bg-brand-primary-dark active:scale-95',
  talaoSearchResults: 'flex flex-col gap-1.5',
  talaoSearchResult: 'flex w-full cursor-pointer items-center justify-between gap-2 rounded-lg border border-[#eee] bg-white px-3 py-2 text-left text-sm transition-colors hover:border-brand-primary hover:bg-brand-primary/5',
  talaoBookRow: 'flex items-center gap-2',
  talaoBookMenuWrap: 'relative',
  talaoBookMenuList: 'absolute top-[calc(100%+4px)] right-0 z-20 flex min-w-44 flex-col gap-0.5 rounded-lg border border-[#ddd] bg-white p-1 shadow-[0_4px_16px_rgba(0,0,0,0.12)]',
  talaoBookMenuItem: 'flex w-full cursor-pointer items-center rounded-md border-0 bg-transparent px-2.5 py-2 text-left text-sm text-brand-text hover:bg-[#f5f5f5]',
  talaoBookMenuItemDanger: 'text-[#b00020]',
  talaoViewLink: 'self-end text-[11px] font-semibold text-brand-primary hover:underline',
  presence: 'fixed bottom-4 left-4 z-[55] flex items-end gap-2.5 animate-[presence-in_.4s_ease-out]',
  presenceAvatar: 'flex size-11 cursor-pointer items-center justify-center rounded-full border-0 bg-brand-primary text-[17px] font-bold text-white shadow-[0_2px_10px_rgba(0,0,0,.22)] hover:bg-brand-primary-dark',
  presenceMessage: 'flex max-w-[min(280px,60vw)] items-center gap-2 rounded-full bg-brand-card py-2.5 pr-2 pl-4 text-[13px] leading-[1.3] shadow-[0_2px_10px_rgba(0,0,0,.16)]',
  pdfPage: 'mx-auto max-w-[1000px] px-4 py-6',
  pdfToolbar: 'mb-5 flex items-center gap-4 border-b border-[#eee] pb-4 print:hidden',
  pdfGrid: 'grid grid-cols-[repeat(auto-fill,minmax(160px,1fr))] gap-4',
  pdfItem: 'break-inside-avoid [&>img]:block [&>img]:aspect-[9/16] [&>img]:w-full [&>img]:rounded-md [&>img]:bg-[#eee] [&>img]:object-cover',
  backLink: 'my-5 inline-flex items-center gap-2 rounded-control px-2 py-1.5 text-sm font-semibold text-brand-primary transition-[background,color,transform] hover:bg-brand-primary/8 hover:text-brand-primary-dark active:scale-[.98]',
  priceLocked: 'my-1 block text-[13px] font-semibold text-brand-primary',
  originalPrice: 'relative text-sm text-brand-muted after:absolute after:inset-x-0 after:top-1/2 after:h-px after:bg-current',
  discountedPrice: 'text-xl font-bold text-brand-primary',
  discountRow: 'my-0.5 flex flex-wrap items-center gap-2',
  discountBadge: 'rounded-full bg-brand-primary px-1.5 py-0.5 text-[11px] font-bold text-white',
  cartHeader: 'flex items-center justify-between border-b border-[#eee] p-4 [&>button]:cursor-pointer [&>button]:border-0 [&>button]:bg-transparent [&>button]:text-xl',
  cartItems: 'flex-1 overflow-y-auto px-4 py-2',
  remove: 'ml-2.5 cursor-pointer border-0 bg-transparent text-xs text-[#b00020] hover:underline',
  removedNotice: 'flex items-center justify-between gap-3 rounded-brand bg-brand-background px-4 py-2.5 text-sm text-brand-muted',
  // Botão de texto genérico (desfazer, "usar meu CEP", "ver itens" etc.) —
  // qualquer ação secundária que deve parecer link clicável, não caixa cheia.
  linkButton: 'cursor-pointer border-0 bg-transparent p-0 text-sm font-semibold text-brand-primary hover:underline disabled:cursor-not-allowed disabled:opacity-40 disabled:hover:no-underline',
  cartGroup: 'border-b border-[#f0f0f0] py-3',
  cartGroupSummary: 'flex items-center gap-2.5',
  cartGroupImage: 'h-16 w-12 shrink-0 rounded-md bg-[#eee]',
  cartGroupInfo: 'min-w-0 flex-1 [&>.name]:text-[13px] [&>.name]:font-semibold [&>.variant]:mt-0.5 [&>.variant]:text-xs [&>.variant]:text-brand-muted',
  cartGroupToggle: 'cursor-pointer border-0 bg-transparent p-1 text-brand-primary hover:underline',
  cartGroupItems: 'mt-2.5 flex flex-col gap-2.5',
  cartGroupEdit: 'mt-2 cursor-pointer self-start border-0 bg-transparent p-0 text-xs font-semibold text-brand-primary hover:underline disabled:opacity-40',
  cartLine: 'flex flex-wrap items-center gap-3.5 gap-y-2.5 max-sm:grid max-sm:grid-cols-[auto_minmax(0,1fr)] max-sm:items-start',
  // A página cheia do carrinho tem controles densos por cor/tamanho; esta
  // miniatura precisa obedecer a linha, nunca o tamanho natural da foto.
  cartLineImage: 'h-16 w-12 flex-none self-start rounded-[5px] bg-[#eee] max-sm:row-span-2 sm:h-24 sm:w-16',
  cartLineField: 'flex shrink-0 flex-col gap-1 [&>label]:text-[10px] [&>label]:tracking-[.03em] [&>label]:text-brand-muted [&>label]:uppercase [&>select]:min-w-28 [&>select]:rounded-md [&>select]:border [&>select]:border-[#ddd] [&>select]:bg-white [&>select]:px-2 [&>select]:py-1.5 [&>select]:text-xs',
  cartLineGrid: 'flex flex-1 flex-wrap items-center gap-3 max-sm:col-span-2 max-sm:w-full',
  cartLineCell: 'flex min-w-[30px] flex-col items-center gap-1 text-[11px] text-brand-muted [&>.size]:font-semibold [&>.size]:text-brand-text',
  cartLinePrice: 'shrink-0 text-right text-xs whitespace-nowrap text-brand-muted',
  cartLineAction: 'shrink-0 cursor-pointer border-0 bg-transparent p-0 text-[11px] text-brand-primary hover:underline disabled:cursor-default disabled:opacity-40',
  cartLineTrash: 'shrink-0 cursor-pointer border-0 bg-transparent p-1 text-[15px] leading-none text-brand-muted hover:text-[#b00020]',
  variantPicker: 'mt-1 flex flex-col gap-3',
  variantFilters: 'flex flex-wrap items-center gap-2',
  variantFilter: 'cursor-pointer rounded-full border border-[#ddd] bg-white px-3 py-1.5 text-xs font-semibold text-brand-muted transition-[border-color,background-color,color,transform] hover:border-brand-primary hover:text-brand-primary active:scale-[.98]',
  variantFilterActive: 'border-brand-primary bg-brand-primary text-white hover:border-brand-primary-dark hover:bg-brand-primary-dark hover:text-white',
  variantFilterPreorder: 'border-[#d9b76c] text-[#87611a] hover:border-[#b9892d] hover:text-[#76500d]',
  variantFilterInStock: 'border-[#9acdae] text-[#247144] hover:border-[#4d9a6d] hover:text-[#1d613a]',
  variantMatrix: 'overflow-x-auto rounded-brand border border-[#eee] bg-white',
  variantMatrixTable: 'w-full min-w-[420px] border-separate border-spacing-0 text-left text-xs',
  variantMatrixHead: 'bg-brand-background text-[10px] font-bold tracking-[.04em] text-brand-muted uppercase',
  variantMatrixHeadCell: 'border-b border-[#eee] px-3 py-2.5 text-center first:min-w-[124px] first:text-left',
  variantMatrixRow: '[&:not(:last-child)>td]:border-b [&:not(:last-child)>td]:border-[#f0f0f0]',
  variantMatrixColor: 'px-3 py-2.5 font-semibold text-brand-text',
  variantMatrixCell: 'min-w-[66px] px-1.5 py-2 text-center align-middle',
  variantMatrixCellEmpty: 'text-brand-muted/60',
  variantMatrixCellOut: 'text-[#b00020]/60',
  variantMatrixCellDimmed: 'opacity-35',
  variantQtyControl: 'inline-flex items-center overflow-hidden rounded-md border border-[#ddd] bg-white shadow-[0_1px_2px_rgba(44,28,36,.04)] [&>button]:flex [&>button]:size-7 [&>button]:cursor-pointer [&>button]:items-center [&>button]:justify-center [&>button]:border-0 [&>button]:bg-transparent [&>button]:text-sm [&>button]:text-brand-primary [&>button]:transition-colors [&>button:hover:not(:disabled)]:bg-brand-background [&>button:disabled]:cursor-not-allowed [&>button:disabled]:text-brand-muted/35 [&>span]:min-w-6 [&>span]:text-center [&>span]:text-xs [&>span]:font-semibold [&>span]:text-brand-text',
  variantQtyPreorder: 'border-[#ecd9aa] bg-[#fffaf0] [&>button]:text-[#87611a]',
  variantQtyExcess: 'ml-1 text-[10px] font-semibold text-[#87611a]',
  cartProduct: 'border-b border-[#f0f0f0] py-3.5 last:border-b-0',
  cartProductHeader: 'mb-2.5 flex items-baseline gap-2 [&>.name]:text-[13px] [&>.name]:font-semibold',
  cartProductLines: 'flex flex-col gap-2.5',
  cartAddColor: 'mt-2.5 cursor-pointer rounded-full border border-dashed border-[#ccc] bg-transparent px-3.5 py-1.5 text-xs text-brand-muted hover:border-brand-primary hover:text-brand-primary',
  colorSelect: 'relative',
  colorSelectTrigger: 'flex min-w-28 cursor-pointer items-center gap-1.5 rounded-md border border-[#ddd] bg-white px-2 py-1.5 text-xs text-brand-text hover:border-brand-primary disabled:cursor-default disabled:opacity-50',
  colorSelectList: 'absolute top-[calc(100%+4px)] left-0 z-5 m-0 flex max-h-[220px] min-w-40 list-none flex-col overflow-y-auto rounded-lg border border-[#ddd] bg-white p-1 shadow-[0_4px_16px_rgba(0,0,0,0.12)]',
  colorSelectOption: 'flex w-full cursor-pointer items-center gap-2 rounded-md border-0 bg-transparent px-2 py-1.5 text-left text-xs text-brand-text hover:bg-[#f5f5f5]',
  swatch: 'inline-block size-3 shrink-0 rounded-full border border-black/15',
  homeFallback: 'static h-auto overflow-hidden bg-linear-to-br from-brand-primary to-brand-primary-dark px-4 py-9 text-center text-white [&>div]:static [&>div]:flex [&>div]:flex-col [&>div]:items-center [&>div]:justify-center [&>div>h1]:mb-1.5 [&>div>h1]:text-[clamp(22px,4vw,36px)]',
  homeSections: 'relative mx-auto h-[var(--canvas-height,auto)] max-w-[1200px] max-sm:flex max-sm:h-auto max-sm:flex-col max-sm:gap-4 max-sm:px-4',
  homeSectionItem: 'absolute left-[var(--x,0px)] top-[var(--y,0px)] h-[var(--h,auto)] w-[var(--w,100%)] overflow-hidden max-sm:static max-sm:h-auto max-sm:w-full max-sm:overflow-visible',
  catalogFooter: 'mt-10 border-t border-border bg-surface text-foreground',
  catalogFooterGrid: 'grid gap-8 py-10 sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1.2fr] lg:gap-12 lg:py-12',
  catalogFooterBrand: 'max-w-sm [&>h2]:mt-1 [&>h2]:text-xl [&>h2]:font-extrabold [&>h2]:tracking-[-0.03em] [&>h2]:text-brand-primary [&>p:last-child]:mt-3 [&>p:last-child]:text-sm [&>p:last-child]:leading-6 [&>p:last-child]:text-muted-foreground',
  catalogFooterEyebrow: 'text-xs font-bold tracking-[0.12em] text-muted-foreground uppercase',
  catalogFooterSection: 'flex flex-col items-start gap-1 [&>h2]:mb-2 [&>h2]:text-sm [&>h2]:font-bold [&>a]:flex [&>a]:min-h-11 [&>a]:items-center [&>a]:gap-2 [&>a]:text-sm [&>a]:text-muted-foreground [&>a]:transition-colors [&>a:hover]:text-brand-primary [&>p]:flex [&>p]:min-h-7 [&>p]:items-center [&>p]:gap-2 [&>p]:text-sm [&>p]:leading-5 [&>p]:text-muted-foreground',
  catalogFooterHours: '!mt-1 !text-xs !leading-5',
  catalogFooterBottom: 'flex flex-col gap-3 border-t border-border py-5 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between [&>nav]:flex [&>nav]:gap-4 [&>nav>a]:underline-offset-4 [&>nav>a:hover]:text-brand-primary [&>nav>a:hover]:underline',
  quickviewHeader: 'flex items-center justify-between border-b border-[#eee] p-4',
  quickviewBody: 'flex-1 overflow-y-auto p-4',
  miniCart: 'flex cursor-pointer items-center gap-2 border-0 bg-transparent p-0 text-[13px] font-semibold whitespace-nowrap text-brand-text',
  presenceMinimize: 'flex size-[22px] cursor-pointer items-center justify-center rounded-full border-0 bg-transparent text-base text-brand-muted hover:bg-brand-background hover:text-brand-text',
  ordersPage: 'pb-[60px]',
  ordersList: 'flex flex-col gap-3',
  orderCard: 'rounded-brand bg-brand-card p-4 shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
  orderCardHeader: 'mb-2 flex flex-wrap items-center justify-between gap-2',
  orderItems: 'flex flex-col gap-2.5',
  orderItem: 'flex gap-2.5',
  orderItemImage: 'h-[72px] w-14 shrink-0 rounded-md bg-[#eee]',
  paymentOptions: 'mb-5 flex max-w-[360px] flex-col gap-2.5',
  paymentOption: 'flex cursor-pointer items-center gap-2.5 rounded-brand border-2 border-transparent bg-brand-card px-4 py-3.5 text-sm font-semibold shadow-[0_1px_4px_rgba(0,0,0,0.08)]',
} as const;
